 SELECT
    A.*,
    COUNT(*) OVER (
        PARTITION BY LONGITUDE, LATITUDE
    ) AS LOCATION_TOTAL_CRIME_COUNT,
    COUNT(*) OVER (
        PARTITION BY MONTH, LONGITUDE, LATITUDE
    ) AS LOCATION_MONTHLY_CRIME_COUNT
FROM {{ source('uk_crime', 'csv_uk_crime') }} A
WHERE LONGITUDE IS NOT NULL
  AND LATITUDE IS NOT NULL
